version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forum
      MYSQL_USER: forum
      MYSQL_PASSWORD: password
    networks: 
      - forum-network
  db-client:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    depends_on:
      - db
    networks: 
      - forum-network
  forum-app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - "../../:/app"
    depends_on:
      - db
    networks:
      - forum-network
  forum-app-dist:
    build:
      context: ../../
      dockerfile: docker/dev/DockerfileDist
    ports:
      - "8010:8000"
    restart: always
    volumes:
      - "../../:/app"
    depends_on:
      - db
      - forum-app
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
